install.packages("data.table")
install.packages("dplyr")
install.packages("purrr")
# Configure could not find suitable mysql/mariadb client library. Try installing:
#  * deb: libmariadbclient-dev (Debian, Ubuntu)
#  * rpm: mariadb-connector-c-devel | mariadb-devel | mysql-devel (Fedora, CentOS, RHEL)
#  * csw: mysql56_dev (Solaris)
#  * brew: mariadb-connector-c (OSX)
install.packages("RMariaDB")
install.packages("rv")
